-- upgrade --
CREATE TABLE IF NOT EXISTS `basemodel` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT
) CHARACTER SET utf8mb4;;

CREATE TABLE IF NOT EXISTS `companies` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;;

CREATE TABLE IF NOT EXISTS `company_names` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `company_id` INT NOT NULL,
    `language` VARCHAR(2) NOT NULL  COMMENT 'KOREA: KO\nENGLISH: EN\nJAPAN: JA' DEFAULT 'KO',
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;-- downgrade --
DROP TABLE IF EXISTS `basemodel`;
DROP TABLE IF EXISTS `companies`;
DROP TABLE IF EXISTS `company_names`;
