-- upgrade --
CREATE TABLE IF NOT EXISTS `tags` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS `tag_names` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `tag_id` INT NOT NULL,
    `language` VARCHAR(2) NOT NULL  COMMENT 'KOREA: KO\nENGLISH: EN\nJAPAN: JA' DEFAULT 'KO',
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;

CREATE TABLE `companies_tags` (`companies_id` INT NOT NULL REFERENCES `companies` (`id`) ON DELETE CASCADE,`tag_id` INT NOT NULL REFERENCES `tags` (`id`) ON DELETE CASCADE) CHARACTER SET utf8mb4;

-- downgrade --
DROP TABLE IF EXISTS `companies_tags`;
DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `tag_names`;
